par(mfrow=c(2,2))
plot(strptime(paste(power2$Date,power2$Time),"%d/%m/%Y %X"),power2$Global_active_power, type="l", xlab="", ylab="Global Active Power (kiloWatts)")
plot(strptime(paste(power2$Date,power2$Time),"%d/%m/%Y %X"),power2$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(strptime(paste(power2$Date,power2$Time),"%d/%m/%Y %X"),power2$Sub_metering_1, type="l", xlab="", ylab="Energy Sub metering")
lines(strptime(paste(power2$Date,power2$Time),"%d/%m/%Y %X"),power2$Sub_metering_2, col="red")
lines(strptime(paste(power2$Date,power2$Time),"%d/%m/%Y %X"),power2$Sub_metering_3, col="blue")
legend("topright", pch=1, col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(strptime(paste(power2$Date,power2$Time),"%d/%m/%Y %X"),power2$Global_reactive_power, type="l", xlab="datetime", ylab="Global Reactive Power")
dev.copy(png,file="plot4.png")
dev.off()
